### ISSUE TITLE
Line in markdown causing confusion for students.

### ISSUE THREAD

**Issue by JulianWard147** [learn-co-curriculum/dsc-regression-model-validation#3]
## Link to Canvas

https://learning.flatironschool.com/courses/5539/assignments/201004?module_item_id=455835

## Issue Subtype

- [] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [X] Other (explain below)

### Source

```
In some cases you will see all of the data being prepared together for expediency, but the best practice is to prepare it separately.
```

### Concern

This line tripped up several students, and generates an impression that data leakage is an inconvenience we only do because it's best practices, as opposed to a serious source of errors. Additionally, it's generally not all that more expedient to preprocess before train test split, whether on a large or small dataset. 

## (Optional) Proposed Solution

Delete the line. Or maybe if there's some case where preprocessing has to happen before TTS, perhaps provide that example?  I can think of a few preprocessing steps that only involve interactions on the same row, so there's no data leakage, but there's still no reason I can think of not to just do those steps after TTS.

## What OS Are You Using?

- [ ] OS X
- [ ] Windows
- [ ] WSL
- [ ] Linux
- [ ] IllumiDesk

## Any Additional Context?

I'm a coach not a student, dropping this in on behalf of Jelly and the 080821 DS cohort. 

README for DS Instructor content implies that raising git issues for small changes like this is preferable to Jira tickets. Not sure if that applies to Canvas materials as well, but I'm generalizing from there.

**Comment by christine-egan42** [comment]
fixed with [ba20eba](https://github.com/learn-co-curriculum/dsc-regression-model-validation/commit/ba20ebacb778f7e25d265a3e01805ffb69f83754)
