### ISSUE TITLE
TypeError in LinearRegression due to mixed data types in feature names

### ISSUE THREAD

**Issue by kev065** [learn-co-curriculum/dsc-regression-model-validation#5]
## Issue Subtype

- [x ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [ ] Other (explain below)

## Describe the Issue
**This is the error I get when I run cell 19**: TypeError Traceback (most recent call last) Cell In[19], line 3 1 from sklearn.linear_model import LinearRegression 2 linreg = LinearRegression() ----> 3 linreg.fit(X_train_tr, y_train) 5 y_hat_train = linreg.predict(X_train_tr) 6 y_hat_test = linreg.predict(X_test_tr) File ~/anaconda3/envs/learn-env/lib/python3.10/site-packages/sklearn/base.py:1474, in fitcontext.<locals>.decorator.<locals>.wrapper(estimator, *args, kwargs) 1467 estimator._validate_params() 1469 with config_context( 1470 skip_parameter_validation=( 1471 prefer_skip_nested_validation or global_skip_validation 1472 ) 1473 ): -> 1474 return fit_method(estimator, *args, kwargs) File ~/anaconda3/envs/learn-env/lib/python3.10/site-packages/sklearn/linear_model/_base.py:578, in LinearRegression.fit(self, X, y, sample_weight) 574 njobs = self.n_jobs 576 accept_sparse = False if self.positive else ["csr", "csc", "coo"] --> 578 X, y = self._validate_data( 579 X, y, accept_sparse=accept_sparse, y_numeric=True, multi_output=True 580 ) 582 has_sw = sample_weight is not None ... 2236 ) 2238 # Only feature names of all strings are supported 2239 if len(types) == 1 and types[0] == "str": Feature names are only supported if all input features have string names, but your input has ['int', 'str'] as feature name / column name types. If you want feature names to be stored and validated, you must convert them all to strings, by using X.columns = X.columns.astype(str) for example. Otherwise you can remove feature / column names from your input data, or convert them all to a non-string data type.
### Source

```
from sklearn.linear_model import LinearRegression
linreg = LinearRegression()
linreg.fit(X_train_tr, y_train)

y_hat_train = linreg.predict(X_train_tr)
y_hat_test = linreg.predict(X_test_tr)
```

### Concern

When using scikit-learn's LinearRegression with a DataFrame containing mixed data types (integers and strings) as feature names, a TypeError is raised during the fit method. This occurs because scikit-learn expects consistent data types for feature names, preferably all strings.

## (Optional) Proposed Solution

Create a code cell just below the heading `Building, Evaluating, and Validating a Model` and add this code there. That should resolve the error: 
\# convert feature names to strings
X_train_tr.columns = X_train_tr.columns.astype(str)
X_test_tr.columns = X_test_tr.columns.astype(str)

## What OS Are You Using?

- [ ] OS X
- [ ] Windows
- [ x] WSL
- [ ] Linux
- [ ] Saturn Cloud from Canvas

**Comment by bpurdy-ds** [comment]
Thank you for raising this issue. We'll take a look. (And we haven't forgot about the one from the 7th.)

**Comment by bpurdy-ds** [comment]
Great proposed solution. Updating now. Thank you.

**Comment by bpurdy-ds** [comment]
Repo updated. Thanks again.
